### ISSUE TITLE
Nice GUI for user interaction

### ISSUE THREAD

**Issue by tepene** [ublue-os/forge#34]
### Describe the feature

I'd like this project to be enhanced with a nice GUI for user interaction because this project should be easy to use and have an option to give you some insights.

some ideas:

- page to launch automation jobs
- page to display all images stored in the registry
- page to edit configuration files

I already did some tests with [ansible semaphore](https://github.com/ublue-os/forge/issues/5#issuecomment-2082466192) which is nice for all the ansible jobs but it also introduces some overhead with provisioning. And it has it's own usage logic which is ok but it's not going to serve us well in the long term.

Maybe [NiceGUI](https://nicegui.io/) is something we could use.

**Comment by tepene** [comment]
[NiceGUI](https://nicegui.io/) combined with [ansible-runner](https://ansible.readthedocs.io/projects/runner/en/latest/python_interface/) could be a good combination

**Comment by tepene** [comment]
I started to play around with [NiceGui](https://nicegui.io/). My efforts are in the [tepne/nicegui](https://github.com/ublue-os/forge/tree/tepene/nicegui) branch.

Here a screenshot how things could look like:

![image](https://github.com/ublue-os/forge/assets/54766327/759ea0d9-51ed-40ff-b502-2c22547f4736)

Some things are still missing before i can MR this to main. Noteworthy:

- [ ] Mount configuration directory from host
- [ ] Add configuration file picker
- [ ] Make sure ansible loads configuration file on each job
- [ ] Make sure ansible-runner jobs run async

**Comment by tepene** [comment]
I added a configuration file picker. Still some quirks to iron out before ready for MR.

![image](https://github.com/ublue-os/forge/assets/54766327/aa7ff94d-d82a-4db3-8daa-22e7ccbc7567)

**Comment by tepene** [comment]
Slowly but steady, making some progress:

[Screencast from 2024-05-08 21-04-00.webm](https://github.com/ublue-os/forge/assets/54766327/9213fac5-1576-4b53-a7cc-c4825ff4224f)

Config data is now stored in a podman volume. For currently unknown reason ansible does not pick up my `--extra-vars` statement. I will investigate that further and apply necessary changes.

**Comment by tepene** [comment]
I was able to fix `--extra-vars`  issue. Configuration is loading now as expected. So, almost there, just need to adapt some changes in the `devcontainer.json` and `forge.sh `

**Comment by castrojo** [comment]
Got a post up! https://universal-blue.discourse.group/t/self-hosters-the-forge-needs-your-eyes-and-hands/1566

**Comment by tepene** [comment]
> Got a post up! https://universal-blue.discourse.group/t/self-hosters-the-forge-needs-your-eyes-and-hands/1566

Thanks, I'll update the docs asap so people are not confused too much.

**Comment by tepene** [comment]
Added some documentation. Hopefully enough fore others to get started.
